"""
MoodTunes AI — Curated Song Catalog
====================================
500+ hand-picked songs across 8 moods.
Each song has:  song_name, artist, album, spotify_id, popularity, genre

Spotify URLs are built as:  https://open.spotify.com/track/<spotify_id>
YouTube URLs are added at runtime by the seeder via YouTube Data API.
"""

SONG_CATALOG = {

    # ══════════════════════════════════════════════════════════════
    #  HAPPY  — upbeat, feel-good, pop, dance, indie-pop
    # ══════════════════════════════════════════════════════════════
    "happy": [
        {"song_name": "Happy",                        "artist": "Pharrell Williams",      "album": "G I R L",                        "spotify_id": "60nZcImufyMA1MKQY3dcCH", "popularity": 87, "genre": "pop"},
        {"song_name": "Good as Hell",                 "artist": "Lizzo",                  "album": "Cuz I Love You",                 "spotify_id": "5yY8Q8EIFGvUtSkvSqMVmz", "popularity": 83, "genre": "pop"},
        {"song_name": "Can't Stop the Feeling!",      "artist": "Justin Timberlake",      "album": "Trolls OST",                     "spotify_id": "1WkMMavIMc4JZ8cfMmxHkI", "popularity": 85, "genre": "pop"},
        {"song_name": "Uptown Funk",                  "artist": "Mark Ronson ft. Bruno Mars", "album": "Uptown Special",             "spotify_id": "32OlwWuMpZ964bob3jDEIQ", "popularity": 89, "genre": "funk"},
        {"song_name": "Walking on Sunshine",          "artist": "Katrina and the Waves",  "album": "Walking on Sunshine",            "spotify_id": "05wIrZSwuaVWhcv5FfqeH0", "popularity": 78, "genre": "pop-rock"},
        {"song_name": "Don't Stop Me Now",            "artist": "Queen",                  "album": "Jazz",                           "spotify_id": "5T8EDUDqKcs6OSOwEsfqG7", "popularity": 86, "genre": "rock"},
        {"song_name": "Dancing Queen",                "artist": "ABBA",                   "album": "Arrival",                        "spotify_id": "0GjEhVFGZW8afUYGChu3Rr", "popularity": 82, "genre": "pop"},
        {"song_name": "I Gotta Feeling",              "artist": "Black Eyed Peas",        "album": "The E.N.D.",                     "spotify_id": "4SqFCjgSBtvMjgoYFfMRZN", "popularity": 81, "genre": "pop"},
        {"song_name": "Shake It Off",                 "artist": "Taylor Swift",           "album": "1989",                           "spotify_id": "0cqRj7pUJDkTCEsJkx8snD", "popularity": 88, "genre": "pop"},
        {"song_name": "Happy Together",               "artist": "The Turtles",            "album": "Happy Together",                 "spotify_id": "6obCxxT1bUuvO0HKqMZ6xl", "popularity": 72, "genre": "pop"},
        {"song_name": "Lovely Day",                   "artist": "Bill Withers",           "album": "Menagerie",                      "spotify_id": "3IKbOdVeD7HjLT1MbRE7ue", "popularity": 75, "genre": "soul"},
        {"song_name": "Best Day of My Life",          "artist": "American Authors",       "album": "Oh, What a Life",                "spotify_id": "3SVAN3BRByDmHOSBGabisW", "popularity": 79, "genre": "indie-pop"},
        {"song_name": "Roar",                         "artist": "Katy Perry",             "album": "Prism",                          "spotify_id": "6DAYV98PFBkeaIEHr9yFKM", "popularity": 82, "genre": "pop"},
        {"song_name": "On Top of the World",          "artist": "Imagine Dragons",        "album": "Night Visions",                  "spotify_id": "2H7PHVdQ3mXqEHXcvclTB0", "popularity": 80, "genre": "indie-pop"},
        {"song_name": "Good Feeling",                 "artist": "Flo Rida",               "album": "Wild Ones",                      "spotify_id": "2CEgGE6aESpnmtfiZwYOKO", "popularity": 76, "genre": "pop"},
        {"song_name": "Happy (We Are)",               "artist": "Pharrell Williams",      "album": "Despicable Me 2 OST",            "spotify_id": "1BSpHMl4IHdxCmHRBIR3DX", "popularity": 74, "genre": "pop"},
        {"song_name": "Sunflower",                    "artist": "Post Malone & Swae Lee", "album": "Spider-Man: Into the Spider-Verse","spotify_id": "3KkXRkHbMCARz0aVfEt68P", "popularity": 90, "genre": "pop"},
        {"song_name": "Good Vibrations",              "artist": "The Beach Boys",         "album": "Smiley Smile",                   "spotify_id": "3YnXiMfBUEVX5pX7FZqhEK", "popularity": 73, "genre": "pop"},
        {"song_name": "Stronger (What Doesn't Kill You)", "artist": "Kelly Clarkson",    "album": "Stronger",                       "spotify_id": "3jbT1LFGTFCkTCTBIF1R4e", "popularity": 78, "genre": "pop"},
        {"song_name": "Blinding Lights",              "artist": "The Weeknd",             "album": "After Hours",                    "spotify_id": "0VjIjW4GlUZAMYd2vXMi3b", "popularity": 95, "genre": "pop"},
        {"song_name": "Levitating",                   "artist": "Dua Lipa",               "album": "Future Nostalgia",               "spotify_id": "463CkQjx2Zk1yXoBuierM9", "popularity": 91, "genre": "pop"},
        {"song_name": "Watermelon Sugar",             "artist": "Harry Styles",           "album": "Fine Line",                      "spotify_id": "6UelLqGlWMcVH1E5c4H7lY", "popularity": 88, "genre": "pop"},
        {"song_name": "As It Was",                    "artist": "Harry Styles",           "album": "Harry's House",                  "spotify_id": "4Dvkj6JhhA12EX05fT7y2e", "popularity": 92, "genre": "pop"},
        {"song_name": "Flowers",                      "artist": "Miley Cyrus",            "album": "Endless Summer Vacation",        "spotify_id": "4Devj9KBiDf8i3OIlDlW7r", "popularity": 89, "genre": "pop"},
        {"song_name": "Anti-Hero",                    "artist": "Taylor Swift",           "album": "Midnights",                      "spotify_id": "0V3wPSX9ygBnCm8psDIegu", "popularity": 93, "genre": "pop"},
        {"song_name": "Dynamite",                     "artist": "BTS",                    "album": "Dynamite",                       "spotify_id": "0yLdNVWF3Srea0uzk55zFn", "popularity": 87, "genre": "k-pop"},
        {"song_name": "Shape of You",                 "artist": "Ed Sheeran",             "album": "Divide",                         "spotify_id": "7qiZfU4dY1lWllzX7mPBI3", "popularity": 93, "genre": "pop"},
        {"song_name": "Happier",                      "artist": "Marshmello & Bastille",  "album": "Happier",                        "spotify_id": "2dpaYNEQHiRxtZbfNsse99", "popularity": 84, "genre": "edm-pop"},
        {"song_name": "Shake Your Body",              "artist": "The Jacksons",           "album": "Destiny",                        "spotify_id": "2Iqg1qtAuY9vBuNAHBl8Dy", "popularity": 68, "genre": "funk"},
        {"song_name": "Happy Nation",                 "artist": "Ace of Base",            "album": "The Sign",                       "spotify_id": "3rqAlVjlBBXXgUbXYqTikF", "popularity": 70, "genre": "pop"},
        {"song_name": "I'm Good (Blue)",              "artist": "David Guetta & Bebe Rexha","album": "I'm Good (Blue)",              "spotify_id": "4uUG5RXrOk84mYEfFvj3cK", "popularity": 88, "genre": "edm"},
        {"song_name": "Cruel Summer",                 "artist": "Taylor Swift",           "album": "Lover",                          "spotify_id": "1BkGiBAESI4vAcGnMn5gH6", "popularity": 91, "genre": "pop"},
        {"song_name": "Unstoppable",                  "artist": "Sia",                    "album": "This Is Acting",                 "spotify_id": "6oHLbWKpGpEO2ikHcLYCdm", "popularity": 80, "genre": "pop"},
        {"song_name": "Here Comes the Sun",           "artist": "The Beatles",            "album": "Abbey Road",                     "spotify_id": "6dGnYIeXmHdcikdzNNDMm2", "popularity": 83, "genre": "rock"},
        {"song_name": "Three Little Birds",           "artist": "Bob Marley",             "album": "Exodus",                         "spotify_id": "6B6kFyLCRsJUBCLm7WTJMK", "popularity": 80, "genre": "reggae"},
        {"song_name": "Soak Up the Sun",              "artist": "Sheryl Crow",            "album": "C'mon C'mon",                    "spotify_id": "1GR8rlKhFGX3LqxnBmEnLG", "popularity": 71, "genre": "pop-rock"},
        {"song_name": "Good Day Sunshine",            "artist": "The Beatles",            "album": "Revolver",                       "spotify_id": "2YKzpPzRHABWW2gbxqbnZf", "popularity": 72, "genre": "pop"},
        {"song_name": "Mr. Brightside",               "artist": "The Killers",            "album": "Hot Fuss",                       "spotify_id": "003vvx7Niy0yvhvHt4a68B", "popularity": 84, "genre": "indie-rock"},
        {"song_name": "Sunday Best",                  "artist": "Surfaces",               "album": "Where the Light Is",             "spotify_id": "5lGsHRFnJnBEPHJuDnSLzh", "popularity": 77, "genre": "indie-pop"},
        {"song_name": "Golden Hour",                  "artist": "JVKE",                   "album": "this is what ____ feels like",   "spotify_id": "5odlY52u43F5BjByhxg7wg", "popularity": 86, "genre": "pop"},
    ],

    # ══════════════════════════════════════════════════════════════
    #  SAD  — emotional, acoustic, indie, ballad
    # ══════════════════════════════════════════════════════════════
    "sad": [
        {"song_name": "The Night We Met",             "artist": "Lord Huron",             "album": "Strange Trails",                 "spotify_id": "3ZMIcOOoG2oI7UXcBbOcYP", "popularity": 83, "genre": "indie-folk"},
        {"song_name": "Someone Like You",             "artist": "Adele",                  "album": "21",                             "spotify_id": "1zwMYTA5nlNjZxYrvBB2pV", "popularity": 88, "genre": "pop"},
        {"song_name": "Fix You",                      "artist": "Coldplay",               "album": "X&Y",                            "spotify_id": "7LVHVU3tWfcxj5aiPFEW4Q", "popularity": 85, "genre": "alternative"},
        {"song_name": "Skinny Love",                  "artist": "Bon Iver",               "album": "For Emma, Forever Ago",          "spotify_id": "2vKIbvLN3OW1NbAXJgqMrV", "popularity": 76, "genre": "indie-folk"},
        {"song_name": "The Sound of Silence",         "artist": "Simon & Garfunkel",      "album": "Wednesday Morning, 3 A.M.",      "spotify_id": "3YfS47QufnLDFA71FUsgCM", "popularity": 79, "genre": "folk"},
        {"song_name": "Let Her Go",                   "artist": "Passenger",              "album": "All the Little Lights",          "spotify_id": "0hjbrzADkPXBnXcgELJFBV", "popularity": 84, "genre": "acoustic"},
        {"song_name": "Hurt",                         "artist": "Johnny Cash",            "album": "American IV: The Man Comes Around","spotify_id": "28cngnQkQ6cabAbmcEDDQZ", "popularity": 81, "genre": "country"},
        {"song_name": "Creep",                        "artist": "Radiohead",              "album": "Pablo Honey",                    "spotify_id": "70LcF31zb1H0PyJoS1Sx1r", "popularity": 80, "genre": "alternative"},
        {"song_name": "Yesterday",                    "artist": "The Beatles",            "album": "Help!",                          "spotify_id": "3BQHpFgAp4l80e1XslIjNI", "popularity": 82, "genre": "pop"},
        {"song_name": "Tears in Heaven",              "artist": "Eric Clapton",           "album": "Rush OST",                       "spotify_id": "3WZAhWhzS7t4VE5tBFxMme", "popularity": 77, "genre": "rock"},
        {"song_name": "Mad World",                    "artist": "Gary Jules",             "album": "Trading Snakeoil for Wolftickets","spotify_id": "3JOVTQ5h8HyvkyadHLGJT1", "popularity": 78, "genre": "alternative"},
        {"song_name": "Everlong",                     "artist": "Foo Fighters",           "album": "The Colour and the Shape",       "spotify_id": "5UWwZ5lm5PKu6eKsHAGxOk", "popularity": 81, "genre": "rock"},
        {"song_name": "Black",                        "artist": "Pearl Jam",              "album": "Ten",                            "spotify_id": "7bDrBCkVVEn9kHRpD5K6dG", "popularity": 75, "genre": "grunge"},
        {"song_name": "All I Want",                   "artist": "Kodaline",               "album": "In a Perfect World",             "spotify_id": "53gOFjbNsGi1IqGjjBiZjX", "popularity": 77, "genre": "indie"},
        {"song_name": "Breathe Me",                   "artist": "Sia",                    "album": "Colour the Small One",           "spotify_id": "6TNBwXwYJHBNpBEbmTiCvn", "popularity": 74, "genre": "pop"},
        {"song_name": "The A Team",                   "artist": "Ed Sheeran",             "album": "Plus",                           "spotify_id": "0VifaBtDVBnvXkJXgHeBuI", "popularity": 77, "genre": "acoustic"},
        {"song_name": "Gravity",                      "artist": "John Mayer",             "album": "Continuum",                      "spotify_id": "4kIwjQklBFlk5Vs7oA1kOR", "popularity": 76, "genre": "pop-rock"},
        {"song_name": "Landslide",                    "artist": "Fleetwood Mac",          "album": "Fleetwood Mac",                  "spotify_id": "1yBEOUXrMEYzZiE7CAr4Co", "popularity": 78, "genre": "rock"},
        {"song_name": "Fast Car",                     "artist": "Tracy Chapman",          "album": "Tracy Chapman",                  "spotify_id": "1MzDsO6BSZF15luo7sOaWP", "popularity": 80, "genre": "folk"},
        {"song_name": "Chasing Cars",                 "artist": "Snow Patrol",            "album": "Eyes Open",                      "spotify_id": "1jZ7PKv8Mx3vYCqjMlTi1c", "popularity": 79, "genre": "alternative"},
        {"song_name": "Liability",                    "artist": "Lorde",                  "album": "Melodrama",                      "spotify_id": "6nzRUiIlVmqaTr2OXpDrEU", "popularity": 75, "genre": "indie-pop"},
        {"song_name": "Skinny",                       "artist": "Billie Eilish",          "album": "Hit Me Hard and Soft",           "spotify_id": "2js5mmkXwKrYLCFHMEE7Lr", "popularity": 82, "genre": "pop"},
        {"song_name": "drivers license",              "artist": "Olivia Rodrigo",         "album": "SOUR",                           "spotify_id": "5wANPM4fQCJwkGd4rN57mH", "popularity": 87, "genre": "pop"},
        {"song_name": "traitor",                      "artist": "Olivia Rodrigo",         "album": "SOUR",                           "spotify_id": "5CZ40GBx1sQ9sh3lD3N7AR", "popularity": 85, "genre": "pop"},
        {"song_name": "Happier",                      "artist": "Olivia Rodrigo",         "album": "SOUR",                           "spotify_id": "2tgnHNIgeMOfqMkGHFMsWg", "popularity": 83, "genre": "pop"},
        {"song_name": "When the Party's Over",        "artist": "Billie Eilish",          "album": "When We All Fall Asleep...",     "spotify_id": "43zdsphuZLzwA9k4DJhU0I", "popularity": 86, "genre": "pop"},
        {"song_name": "Ocean Eyes",                   "artist": "Billie Eilish",          "album": "Ocean Eyes",                     "spotify_id": "5Ayl2emCbMFaMHMkBVFr6d", "popularity": 84, "genre": "pop"},
        {"song_name": "Half the World Away",          "artist": "Oasis",                  "album": "The Masterplan",                 "spotify_id": "1yH9WT5GALKDpBYLdGjKn8", "popularity": 71, "genre": "britpop"},
        {"song_name": "The Scientist",                "artist": "Coldplay",               "album": "A Rush of Blood to the Head",    "spotify_id": "75JFxkI2RXiU7L9VmtcO4s", "popularity": 84, "genre": "alternative"},
        {"song_name": "Broken",                       "artist": "lovelytheband",          "album": "finding it hard to smile",       "spotify_id": "1YnopD3T4HiDyBQq2DKXEZ", "popularity": 76, "genre": "indie-pop"},
        {"song_name": "Unwell",                       "artist": "Matchbox Twenty",        "album": "More Than You Think You Are",    "spotify_id": "1sXBImF5xMnf1BnXCBtjb5", "popularity": 70, "genre": "rock"},
        {"song_name": "Iris",                         "artist": "Goo Goo Dolls",          "album": "Dizzy Up the Girl",              "spotify_id": "6Qyc6fS4DsZjB2mRW9DsQs", "popularity": 83, "genre": "rock"},
        {"song_name": "Come As You Are",              "artist": "Nirvana",                "album": "Nevermind",                      "spotify_id": "3sFDHuhBFBwNAhWCLFnmMN", "popularity": 83, "genre": "grunge"},
        {"song_name": "Leave the Door Open",          "artist": "Bruno Mars, Anderson .Paak","album": "An Evening with Silk Sonic",  "spotify_id": "7xDT2GNpSBJlnABGJ6FBwu", "popularity": 83, "genre": "soul"},
        {"song_name": "Falling",                      "artist": "Harry Styles",           "album": "Fine Line",                     "spotify_id": "1BNHE4Kvkj0Kgbs5WZAXde", "popularity": 84, "genre": "pop"},
        {"song_name": "TV",                           "artist": "Billie Eilish",          "album": "Happier Than Ever",              "spotify_id": "4jvGA7xsEPuqmKW5HLJRoB", "popularity": 83, "genre": "pop"},
        {"song_name": "Exile",                        "artist": "Taylor Swift ft. Bon Iver","album": "Folklore",                    "spotify_id": "4D7BCuvgdJlYvlX5WlN54t", "popularity": 84, "genre": "indie-folk"},
        {"song_name": "willow",                       "artist": "Taylor Swift",           "album": "Evermore",                      "spotify_id": "0KHEzmSb0WQHYV3lQ3XTIB", "popularity": 82, "genre": "indie-folk"},
        {"song_name": "Midnight Rain",                "artist": "Taylor Swift",           "album": "Midnights",                     "spotify_id": "1ISbH0qL4QDiFHFVP4EIBG", "popularity": 80, "genre": "pop"},
        {"song_name": "Without Me",                   "artist": "Halsey",                 "album": "Manic",                         "spotify_id": "5hVghJ4KaYES3BFPATCiRp", "popularity": 83, "genre": "pop"},
    ],

    # ══════════════════════════════════════════════════════════════
    #  ANGRY  — rock, metal, punk, intense hip-hop
    # ══════════════════════════════════════════════════════════════
    "angry": [
        {"song_name": "Break Stuff",                  "artist": "Limp Bizkit",            "album": "Significant Other",              "spotify_id": "2dMU7PBDLCV1KnC7pzQgL9", "popularity": 73, "genre": "nu-metal"},
        {"song_name": "Bodies",                       "artist": "Drowning Pool",          "album": "Sinner",                         "spotify_id": "2LJUHdqCCzKOwFAiPRNaWN", "popularity": 70, "genre": "hard-rock"},
        {"song_name": "Killing in the Name",          "artist": "Rage Against the Machine","album": "Rage Against the Machine",      "spotify_id": "59WN2psjkt1tyaxjspN8fp", "popularity": 78, "genre": "rap-metal"},
        {"song_name": "Numb",                         "artist": "Linkin Park",            "album": "Meteora",                        "spotify_id": "6Wltnbq38ZW7gJPOLyGNyE", "popularity": 83, "genre": "nu-metal"},
        {"song_name": "In the End",                   "artist": "Linkin Park",            "album": "Hybrid Theory",                  "spotify_id": "60a0Rd6pjrkxjPbaKzXjfq", "popularity": 84, "genre": "nu-metal"},
        {"song_name": "Given Up",                     "artist": "Linkin Park",            "album": "Minutes to Midnight",            "spotify_id": "06gNduJfmOhTAzijufbqcl", "popularity": 73, "genre": "nu-metal"},
        {"song_name": "Bulls on Parade",              "artist": "Rage Against the Machine","album": "Evil Empire",                    "spotify_id": "1R0a2iXumgCiFb7xQjzbaS", "popularity": 75, "genre": "rap-metal"},
        {"song_name": "Enter Sandman",                "artist": "Metallica",              "album": "Metallica (Black Album)",        "spotify_id": "6GCXFnKfHVXnA07WgA5ZKT", "popularity": 81, "genre": "metal"},
        {"song_name": "Smells Like Teen Spirit",      "artist": "Nirvana",                "album": "Nevermind",                      "spotify_id": "5ghIJDpPoe3CfHMGu71E6T", "popularity": 84, "genre": "grunge"},
        {"song_name": "You Oughta Know",              "artist": "Alanis Morissette",      "album": "Jagged Little Pill",             "spotify_id": "0NRwELr3sWAIyuVdVFLyy7", "popularity": 73, "genre": "alternative"},
        {"song_name": "Figured You Out",              "artist": "Nickelback",             "album": "The Long Road",                  "spotify_id": "0gRR2nCRJKuGFu3VGEkWRz", "popularity": 69, "genre": "hard-rock"},
        {"song_name": "Down with the Sickness",       "artist": "Disturbed",              "album": "The Sickness",                   "spotify_id": "4rELFrBOJkRxYKmjlHkN7X", "popularity": 72, "genre": "metal"},
        {"song_name": "Before He Cheats",             "artist": "Carrie Underwood",       "album": "Some Hearts",                    "spotify_id": "4hRmorgFnGklFOSlECMsRQ", "popularity": 75, "genre": "country"},
        {"song_name": "Lose Yourself",                "artist": "Eminem",                 "album": "8 Mile OST",                     "spotify_id": "5Z01UMMf7V1o0MzF86s6WJ", "popularity": 85, "genre": "hip-hop"},
        {"song_name": "The Way I Am",                 "artist": "Eminem",                 "album": "The Marshall Mathers LP",        "spotify_id": "0S8xsXLPOXMnQzuCmFoM8P", "popularity": 74, "genre": "hip-hop"},
        {"song_name": "Run This Town",                "artist": "Jay-Z ft. Rihanna & Kanye","album": "The Blueprint 3",             "spotify_id": "3D9MFhEqNJRr4rJQbXNqhA", "popularity": 74, "genre": "hip-hop"},
        {"song_name": "Power",                        "artist": "Kanye West",             "album": "My Beautiful Dark Twisted Fantasy","spotify_id": "2gZUPNdnz5Y45eiGxpHGSc", "popularity": 79, "genre": "hip-hop"},
        {"song_name": "Stronger",                     "artist": "Kanye West",             "album": "Graduation",                     "spotify_id": "0gplL1WMoJ6iYaPgMCL0gX", "popularity": 82, "genre": "hip-hop"},
        {"song_name": "99 Problems",                  "artist": "Jay-Z",                  "album": "The Black Album",                "spotify_id": "4yCIkbBTrqGkFIWGIuFOsD", "popularity": 78, "genre": "hip-hop"},
        {"song_name": "Sabotage",                     "artist": "Beastie Boys",           "album": "Ill Communication",              "spotify_id": "3L5sQHjWotADeD9qYq8Yse", "popularity": 75, "genre": "hip-hop"},
        {"song_name": "How You Like That",            "artist": "BLACKPINK",              "album": "How You Like That",              "spotify_id": "3J78GHGMWxhA7vHKMpJBlD", "popularity": 82, "genre": "k-pop"},
        {"song_name": "Riot",                         "artist": "Three Days Grace",       "album": "One-X",                          "spotify_id": "4dkCdM6kEZOJpx2p2rLDk4", "popularity": 68, "genre": "hard-rock"},
        {"song_name": "Animal I Have Become",         "artist": "Three Days Grace",       "album": "One-X",                          "spotify_id": "3BmMFOOobsuXW9j8qc0b8W", "popularity": 70, "genre": "hard-rock"},
        {"song_name": "Walk",                         "artist": "Pantera",                "album": "Vulgar Display of Power",        "spotify_id": "3krGBmBKJkMJgLuGFmRWPs", "popularity": 71, "genre": "metal"},
        {"song_name": "Freak on a Leash",             "artist": "Korn",                   "album": "Follow the Leader",              "spotify_id": "3ZFTkvIE7kyPt6Nu3A4L86", "popularity": 69, "genre": "nu-metal"},
        {"song_name": "Beautiful People",             "artist": "Marilyn Manson",         "album": "Antichrist Superstar",           "spotify_id": "01Qr2IJkSbIbEk1Pv0jlBV", "popularity": 68, "genre": "industrial-metal"},
        {"song_name": "Chop Suey!",                   "artist": "System of a Down",       "album": "Toxicity",                       "spotify_id": "2DlHlPMa4M17kufBvI2lEN", "popularity": 78, "genre": "metal"},
        {"song_name": "BYOB",                         "artist": "System of a Down",       "album": "Mezmerize",                      "spotify_id": "2MKGQOFnEDTLqMXCBFbfBQ", "popularity": 74, "genre": "metal"},
        {"song_name": "Faint",                        "artist": "Linkin Park",            "album": "Meteora",                        "spotify_id": "06HL4z0CvFAxyc27GXpf02", "popularity": 77, "genre": "nu-metal"},
        {"song_name": "Crawling",                     "artist": "Linkin Park",            "album": "Hybrid Theory",                  "spotify_id": "6Rb2JEQTFf1kfhWAT5M1H6", "popularity": 76, "genre": "nu-metal"},
        {"song_name": "Headstrong",                   "artist": "Trapt",                  "album": "Trapt",                          "spotify_id": "5O1NHDGjV6xCjqoWmYovnz", "popularity": 66, "genre": "hard-rock"},
        {"song_name": "Pressure",                     "artist": "Muse",                   "album": "Simulation Theory",              "spotify_id": "3Kw4GRsMJEOIlDMIkJd9ON", "popularity": 68, "genre": "rock"},
        {"song_name": "Supermassive Black Hole",      "artist": "Muse",                   "album": "Black Holes and Revelations",    "spotify_id": "4fJyzEiLOFVMtVwY6n43eE", "popularity": 78, "genre": "rock"},
        {"song_name": "How You Remind Me",            "artist": "Nickelback",             "album": "Silver Side Up",                 "spotify_id": "7LiJFPOPivEDdLjAFD4P6f", "popularity": 73, "genre": "rock"},
        {"song_name": "Du Hast",                      "artist": "Rammstein",              "album": "Sehnsucht",                      "spotify_id": "2Gq1QBwGsEJPqjNxBTHcJV", "popularity": 73, "genre": "industrial-metal"},
        {"song_name": "Radioactive",                  "artist": "Imagine Dragons",        "album": "Night Visions",                  "spotify_id": "69yfbpvmkIaB10msnKT9UP", "popularity": 84, "genre": "alternative"},
        {"song_name": "Whatever It Takes",            "artist": "Imagine Dragons",        "album": "Evolve",                         "spotify_id": "52KNXGGcGPaHGrGFyMHtJZ", "popularity": 80, "genre": "alternative"},
        {"song_name": "Demons",                       "artist": "Imagine Dragons",        "album": "Night Visions",                  "spotify_id": "0qdBvBnPpFpY5ZMHfvHWlN", "popularity": 82, "genre": "alternative"},
        {"song_name": "Wrecked",                      "artist": "Imagine Dragons",        "album": "Mercury - Act 1",                "spotify_id": "6y3SdvM0pNxIopwu0YWRMU", "popularity": 76, "genre": "alternative"},
        {"song_name": "Enemy",                        "artist": "Imagine Dragons & JID",  "album": "Enemy",                          "spotify_id": "5QO79kh1waicV47BqGRL3g", "popularity": 86, "genre": "alternative"},
    ],

    # ══════════════════════════════════════════════════════════════
    #  ROMANTIC  — love songs, soul, R&B, ballad
    # ══════════════════════════════════════════════════════════════
    "romantic": [
        {"song_name": "Perfect",                      "artist": "Ed Sheeran",             "album": "Divide",                         "spotify_id": "0tgVpDi06FyKpA1z0VMD4v", "popularity": 89, "genre": "pop"},
        {"song_name": "All of Me",                    "artist": "John Legend",            "album": "Love in the Future",             "spotify_id": "3U4isOIWM3VvDubwSI3y7a", "popularity": 87, "genre": "soul"},
        {"song_name": "Make You Feel My Love",        "artist": "Adele",                  "album": "19",                             "spotify_id": "5OdTLrWBlMGMPgXMBqrLkM", "popularity": 82, "genre": "pop"},
        {"song_name": "A Thousand Years",             "artist": "Christina Perri",        "album": "The Twilight Saga: Breaking Dawn","spotify_id": "6lanRgr6wXibZr8KgzXxBl", "popularity": 83, "genre": "pop"},
        {"song_name": "Can't Help Falling in Love",  "artist": "Elvis Presley",           "album": "Blue Hawaii",                    "spotify_id": "44AyOl4qwyHcd65Vu90lDe", "popularity": 81, "genre": "pop"},
        {"song_name": "Just the Way You Are",         "artist": "Bruno Mars",             "album": "Doo-Wops & Hooligans",           "spotify_id": "7BqBn9nzAq8spo5e7cZ0dJ", "popularity": 85, "genre": "pop"},
        {"song_name": "Unchained Melody",             "artist": "Righteous Brothers",     "album": "Just Once in My Life",           "spotify_id": "7fY6OPBpnSbk7CsxuBmHRv", "popularity": 78, "genre": "soul"},
        {"song_name": "At Last",                      "artist": "Etta James",             "album": "At Last!",                       "spotify_id": "2RpHHJltvhgGdAqEPIoBtl", "popularity": 78, "genre": "soul"},
        {"song_name": "The Way You Look Tonight",     "artist": "Frank Sinatra",          "album": "Songs for Swingin' Lovers!",     "spotify_id": "6VfJG4iLJjWCsaP0X9H6V8", "popularity": 74, "genre": "jazz"},
        {"song_name": "I Will Always Love You",       "artist": "Whitney Houston",        "album": "The Bodyguard OST",              "spotify_id": "4eHbdreAnSOrDDsFfc4Fpm", "popularity": 83, "genre": "r-n-b"},
        {"song_name": "My Heart Will Go On",          "artist": "Celine Dion",            "album": "Let's Talk About Love",          "spotify_id": "3hRV0jL3vUpRrcy398teAU", "popularity": 82, "genre": "pop"},
        {"song_name": "Thinking Out Loud",            "artist": "Ed Sheeran",             "album": "X",                              "spotify_id": "34gCuhDGsG4bRPIf9bb02f", "popularity": 84, "genre": "pop"},
        {"song_name": "Everything I Do",              "artist": "Bryan Adams",            "album": "Waking Up the Neighbours",       "spotify_id": "1r0MKhAZmDqVWKoJNnRILS", "popularity": 74, "genre": "rock"},
        {"song_name": "When a Man Loves a Woman",     "artist": "Percy Sledge",           "album": "When a Man Loves a Woman",       "spotify_id": "7obUjYRHMIuY7VzRjpAGIi", "popularity": 72, "genre": "soul"},
        {"song_name": "Have I Told You Lately",       "artist": "Rod Stewart",            "album": "Vagabond Heart",                 "spotify_id": "0o7ERV7OEZMV7V1YXVBV2E", "popularity": 71, "genre": "pop"},
        {"song_name": "Die for You",                  "artist": "The Weeknd",             "album": "Starboy",                        "spotify_id": "2LBqCSwhJGcFQeTHMVGwy3", "popularity": 86, "genre": "r-n-b"},
        {"song_name": "Earned It",                    "artist": "The Weeknd",             "album": "Fifty Shades of Grey OST",       "spotify_id": "34x6WnkKp9Y4bGDEBbCWYC", "popularity": 83, "genre": "r-n-b"},
        {"song_name": "Love Story",                   "artist": "Taylor Swift",           "album": "Fearless",                       "spotify_id": "1vrd6UOGamcKNGnSHJQlSt", "popularity": 84, "genre": "pop"},
        {"song_name": "Lover",                        "artist": "Taylor Swift",           "album": "Lover",                          "spotify_id": "1dGr1c8CrMLDpV6mPbImSI", "popularity": 82, "genre": "pop"},
        {"song_name": "Enchanted",                    "artist": "Taylor Swift",           "album": "Speak Now",                      "spotify_id": "7gQMDCRYGsRYTYn5BQlxfQ", "popularity": 79, "genre": "pop"},
        {"song_name": "Nothing's Gonna Stop Us Now",  "artist": "Starship",               "album": "No Protection",                  "spotify_id": "0gCBOGdyqDHUlm5cAjL0Lg", "popularity": 69, "genre": "pop-rock"},
        {"song_name": "I'd Do Anything for Love",     "artist": "Meat Loaf",              "album": "Bat Out of Hell II",             "spotify_id": "0iqCGADSmwOBZiJrRmgwGZ", "popularity": 73, "genre": "rock"},
        {"song_name": "Feel So Close",                "artist": "Calvin Harris",          "album": "18 Months",                      "spotify_id": "0cmQiPMu5JiETGpqTFpyAe", "popularity": 77, "genre": "edm"},
        {"song_name": "I Want to Know What Love Is",  "artist": "Foreigner",              "album": "Agent Provocateur",              "spotify_id": "3EYTZ9VtGFhkivezHr1Q5o", "popularity": 73, "genre": "rock"},
        {"song_name": "Still Into You",               "artist": "Paramore",               "album": "Paramore",                       "spotify_id": "3BGZH7KDOaRRKIELe3Kbpn", "popularity": 78, "genre": "pop-rock"},
        {"song_name": "First Time Ever I Saw Your Face","artist": "Roberta Flack",       "album": "First Take",                     "spotify_id": "78XGQPFDhFLvCQ8oKPbMNu", "popularity": 68, "genre": "soul"},
        {"song_name": "How Long Will I Love You",     "artist": "Ellie Goulding",         "album": "Halcyon Days",                   "spotify_id": "2D8mGG2UQ3GijSnSHdnpTy", "popularity": 73, "genre": "pop"},
        {"song_name": "Marry You",                    "artist": "Bruno Mars",             "album": "Doo-Wops & Hooligans",           "spotify_id": "0gM2ATgCcBmgpvBkbTL5jR", "popularity": 79, "genre": "pop"},
        {"song_name": "XO",                           "artist": "Beyoncé",                "album": "Beyoncé",                        "spotify_id": "5kHT9FFbhKcFpL1CAjcalI", "popularity": 75, "genre": "r-n-b"},
        {"song_name": "Halo",                         "artist": "Beyoncé",                "album": "I Am... Sasha Fierce",           "spotify_id": "4JiNYMsUxZFMZsR5cCqfaX", "popularity": 82, "genre": "r-n-b"},
        {"song_name": "Say You Won't Let Go",         "artist": "James Arthur",           "album": "Back from the Edge",             "spotify_id": "5uCax9HTNlzGybIStD3vDh", "popularity": 84, "genre": "pop"},
        {"song_name": "Give Me Love",                 "artist": "Ed Sheeran",             "album": "Plus",                           "spotify_id": "3Eivm2KnnFW3eSs9fFEkCv", "popularity": 76, "genre": "acoustic"},
        {"song_name": "Tenerife Sea",                 "artist": "Ed Sheeran",             "album": "X",                              "spotify_id": "6kFOsUrFkWO7f27hzX8pRs", "popularity": 76, "genre": "pop"},
        {"song_name": "Amazed",                       "artist": "Lonestar",               "album": "Lonely Grill",                   "spotify_id": "59Ii6JrGJygFbzfBdwWAaB", "popularity": 70, "genre": "country"},
        {"song_name": "God Only Knows",               "artist": "The Beach Boys",         "album": "Pet Sounds",                     "spotify_id": "5R2atnE3XAJxVIJh66JKPF", "popularity": 73, "genre": "pop"},
        {"song_name": "Lucky",                        "artist": "Jason Mraz & Colbie Caillat","album": "We Sing. We Dance.",         "spotify_id": "6N2MBEQJxNLb0MnFUq5a9U", "popularity": 75, "genre": "acoustic"},
        {"song_name": "I'm Yours",                    "artist": "Jason Mraz",             "album": "We Sing. We Dance.",             "spotify_id": "1EzrEOXmMH3G43AXT1y7pA", "popularity": 79, "genre": "acoustic"},
        {"song_name": "Bloom",                        "artist": "The Paper Kites",        "album": "Twelvefour",                     "spotify_id": "3ig3Dz0OLYZO4MxkBSZM1r", "popularity": 75, "genre": "indie-folk"},
        {"song_name": "Electric Love",                "artist": "BØRNS",                  "album": "Dopamine",                       "spotify_id": "2GiJYvgVaD2HtM8GqD9EgQ", "popularity": 77, "genre": "indie-pop"},
        {"song_name": "Space Song",                   "artist": "Beach House",            "album": "Depression Cherry",              "spotify_id": "6gFsoIwbtivLhgDmFUFMwA", "popularity": 76, "genre": "dream-pop"},
    ],

    # ══════════════════════════════════════════════════════════════
    #  RELAXED  — lo-fi, ambient, acoustic chill, bossa nova
    # ══════════════════════════════════════════════════════════════
    "relaxed": [
        {"song_name": "Weightless",                   "artist": "Marconi Union",          "album": "Weightless",                     "spotify_id": "6qqNVTkY8uBg9cP3Jd7DAH", "popularity": 65, "genre": "ambient"},
        {"song_name": "Clair de Lune",                "artist": "Claude Debussy",         "album": "Suite bergamasque",              "spotify_id": "4Tr4HkA7PwTv1Gp1jCtRxR", "popularity": 74, "genre": "classical"},
        {"song_name": "Gymnopédie No. 1",             "artist": "Erik Satie",             "album": "Gymnopédies",                    "spotify_id": "5NGtFXVpXSvwunEIGeviY3", "popularity": 72, "genre": "classical"},
        {"song_name": "Here Comes the Sun",           "artist": "The Beatles",            "album": "Abbey Road",                     "spotify_id": "6dGnYIeXmHdcikdzNNDMm2", "popularity": 83, "genre": "rock"},
        {"song_name": "Strawberry Fields Forever",    "artist": "The Beatles",            "album": "Magical Mystery Tour",           "spotify_id": "3Am0IbOxmvlSXro7N5iSfz", "popularity": 77, "genre": "psychedelic"},
        {"song_name": "The Girl from Ipanema",        "artist": "Stan Getz & João Gilberto","album": "Getz/Gilberto",               "spotify_id": "5V4yOdmBLvFIbIOqIeIQJv", "popularity": 72, "genre": "bossa-nova"},
        {"song_name": "Fly Me to the Moon",           "artist": "Frank Sinatra",          "album": "It Might as Well Be Swing",      "spotify_id": "5b7OgDCDTkjBaeFZqFMJVK", "popularity": 76, "genre": "jazz"},
        {"song_name": "What a Wonderful World",       "artist": "Louis Armstrong",        "album": "What a Wonderful World",         "spotify_id": "29U7stRjqHU6rMiS8BfaI9", "popularity": 79, "genre": "jazz"},
        {"song_name": "Somewhere Over the Rainbow",   "artist": "Israel Kamakawiwoole",   "album": "Facing Future",                  "spotify_id": "1GablzY5qFcGDx0xyOaLXr", "popularity": 76, "genre": "acoustic"},
        {"song_name": "Better Together",              "artist": "Jack Johnson",           "album": "In Between Dreams",              "spotify_id": "0FDzzruyVECATHd3yZqZ5L", "popularity": 77, "genre": "acoustic"},
        {"song_name": "Banana Pancakes",              "artist": "Jack Johnson",           "album": "In Between Dreams",              "spotify_id": "0jZDBFZvLiO5oIoGMpyaXy", "popularity": 73, "genre": "acoustic"},
        {"song_name": "Sitting, Waiting, Wishing",    "artist": "Jack Johnson",           "album": "In Between Dreams",              "spotify_id": "3EJcvIc9MkM01TqalmPyxa", "popularity": 71, "genre": "acoustic"},
        {"song_name": "Sunset Lover",                 "artist": "Petit Biscuit",          "album": "Presence",                       "spotify_id": "2VqnpAYzWqOFhRIbgLxKYM", "popularity": 69, "genre": "chillwave"},
        {"song_name": "Coffee",                       "artist": "beabadoobee",            "album": "Loveworm",                       "spotify_id": "7E5BFMjUo5a3AzQb0aJ4G0", "popularity": 76, "genre": "indie"},
        {"song_name": "Retrograde",                   "artist": "James Blake",            "album": "Overgrown",                      "spotify_id": "2dgOxkZkExHTj7lBbkGSKA", "popularity": 72, "genre": "electronic"},
        {"song_name": "Holocene",                     "artist": "Bon Iver",               "album": "Bon Iver, Bon Iver",             "spotify_id": "7sOR7gk6XKnHopCAUSFVBo", "popularity": 74, "genre": "indie-folk"},
        {"song_name": "Re: Stacks",                   "artist": "Bon Iver",               "album": "For Emma, Forever Ago",          "spotify_id": "2Ck5LW0nqDvJqF0vHJUwmC", "popularity": 67, "genre": "indie-folk"},
        {"song_name": "Pink + White",                 "artist": "Frank Ocean",            "album": "Blonde",                         "spotify_id": "3xKsf9qdS1CyvXSMEid6g8", "popularity": 78, "genre": "r-n-b"},
        {"song_name": "Nights",                       "artist": "Frank Ocean",            "album": "Blonde",                         "spotify_id": "7eqoqGkKwgOaWNNHx90uEZ", "popularity": 76, "genre": "r-n-b"},
        {"song_name": "Sunday Morning",               "artist": "Maroon 5",               "album": "Songs About Jane",               "spotify_id": "3hRMk3HPnGITwp6BUQPNEI", "popularity": 78, "genre": "pop"},
        {"song_name": "Put It All on Me",             "artist": "Ed Sheeran",             "album": "No.6 Collaborations Project",    "spotify_id": "5bMBwIvkdBl7G3D8a8LiOW", "popularity": 70, "genre": "acoustic"},
        {"song_name": "Featherstone",                 "artist": "The Paper Kites",        "album": "States",                         "spotify_id": "5GWoXPsTQylMuaZ84PC563", "popularity": 66, "genre": "indie-folk"},
        {"song_name": "Motion Picture Soundtrack",    "artist": "Radiohead",              "album": "Kid A",                          "spotify_id": "3PHCnPVOERuO0ICxqjN7bI", "popularity": 67, "genre": "alternative"},
        {"song_name": "First Breath After Coma",      "artist": "Explosions in the Sky",  "album": "The Earth Is Not a Cold Dead Place","spotify_id": "0GTz1R2fFbQKaaSZt2GFEG", "popularity": 64, "genre": "post-rock"},
        {"song_name": "Do I Wanna Know?",             "artist": "Arctic Monkeys",         "album": "AM",                             "spotify_id": "5FVd6KXrgO9B3JPmC8OPst", "popularity": 85, "genre": "indie-rock"},
        {"song_name": "505",                          "artist": "Arctic Monkeys",         "album": "Favourite Worst Nightmare",      "spotify_id": "0BxE4FqsDD1Ot4YuBXwAPp", "popularity": 82, "genre": "indie-rock"},
        {"song_name": "Take It Easy",                 "artist": "Eagles",                 "album": "Eagles",                         "spotify_id": "4zCH9qm4R2DADamUHMCuqm", "popularity": 75, "genre": "rock"},
        {"song_name": "Peaceful Easy Feeling",        "artist": "Eagles",                 "album": "Eagles",                         "spotify_id": "3wJpKtbHy9QNxFz6cHAjXG", "popularity": 71, "genre": "rock"},
        {"song_name": "The Sound of Silence",         "artist": "Disturbed",              "album": "Immortalized",                   "spotify_id": "09TLDGSBiHGj08hT6SHjz6", "popularity": 79, "genre": "metal"},
        {"song_name": "River Flows in You",           "artist": "Yiruma",                 "album": "First Love",                     "spotify_id": "4Ac1pZhLpOb5RvSA4YBkFx", "popularity": 74, "genre": "classical"},
        {"song_name": "Experience",                   "artist": "Ludovico Einaudi",       "album": "In a Time Lapse",                "spotify_id": "1BncfTJAWtL8MUBK3NCJDO", "popularity": 73, "genre": "classical"},
        {"song_name": "Divenire",                     "artist": "Ludovico Einaudi",       "album": "Divenire",                       "spotify_id": "05glPbZE7kB1oKIwt5QMQK", "popularity": 69, "genre": "classical"},
        {"song_name": "Nuvole Bianche",               "artist": "Ludovico Einaudi",       "album": "Una Mattina",                    "spotify_id": "1tpXaFOLiVEQD0IhcRkdUV", "popularity": 72, "genre": "classical"},
        {"song_name": "Falling",                      "artist": "Novo Amor",              "album": "Bathing Beach",                  "spotify_id": "1x5vTH5mzMRaUBNHOHkEJv", "popularity": 67, "genre": "indie-folk"},
        {"song_name": "All I Want",                   "artist": "Dermot Kennedy",         "album": "Without Fear",                   "spotify_id": "1TCOkMlQlL9mM0bSHAqZCa", "popularity": 71, "genre": "acoustic"},
        {"song_name": "Comptine d'un autre été",      "artist": "Yann Tiersen",           "album": "Amélie OST",                     "spotify_id": "2ZPzKMM1bqbcVRJl9m3zFI", "popularity": 73, "genre": "classical"},
        {"song_name": "Blue Ridge Mountains",         "artist": "Fleet Foxes",            "album": "Fleet Foxes",                    "spotify_id": "0rIMkzaEdXKzlvLBFcJvZh", "popularity": 66, "genre": "indie-folk"},
        {"song_name": "White Winter Hymnal",          "artist": "Fleet Foxes",            "album": "Fleet Foxes",                    "spotify_id": "1dNevAMFsRxDiHyEeq5hft", "popularity": 67, "genre": "indie-folk"},
        {"song_name": "Bloom",                        "artist": "Novo Amor",              "album": "Bathing Beach",                  "spotify_id": "1x5vTH5mzMRaUBNHOHkEJv", "popularity": 68, "genre": "indie-folk"},
        {"song_name": "Japan",                        "artist": "Death Cab for Cutie",    "album": "Thank You for Today",            "spotify_id": "1YnopD3T4HiDyBQq2DKXEZ", "popularity": 65, "genre": "indie"},
    ],

    # ══════════════════════════════════════════════════════════════
    #  MOTIVATIONAL  — workout, hip-hop, power anthems
    # ══════════════════════════════════════════════════════════════
    "motivational": [
        {"song_name": "Eye of the Tiger",             "artist": "Survivor",               "album": "Eye of the Tiger",               "spotify_id": "2HHtWyy5CgaQbC7XSoOb0e", "popularity": 82, "genre": "rock"},
        {"song_name": "Lose Yourself",                "artist": "Eminem",                 "album": "8 Mile OST",                     "spotify_id": "5Z01UMMf7V1o0MzF86s6WJ", "popularity": 85, "genre": "hip-hop"},
        {"song_name": "Till I Collapse",              "artist": "Eminem",                 "album": "The Eminem Show",                "spotify_id": "4QjkBxUBUUMY0JJo2tGNbq", "popularity": 82, "genre": "hip-hop"},
        {"song_name": "Not Afraid",                   "artist": "Eminem",                 "album": "Recovery",                       "spotify_id": "66s7GNGbFTVPFbZmBVQ5XH", "popularity": 80, "genre": "hip-hop"},
        {"song_name": "HUMBLE.",                      "artist": "Kendrick Lamar",         "album": "DAMN.",                          "spotify_id": "7KXjTSCq5nL1LoYtL7XAwS", "popularity": 83, "genre": "hip-hop"},
        {"song_name": "DNA.",                         "artist": "Kendrick Lamar",         "album": "DAMN.",                          "spotify_id": "6HZILIRieu8S0iqY8kIKhj", "popularity": 81, "genre": "hip-hop"},
        {"song_name": "LOYALTY.",                     "artist": "Kendrick Lamar",         "album": "DAMN.",                          "spotify_id": "3UMZcUZoF2V6iNwZOv1hO5", "popularity": 78, "genre": "hip-hop"},
        {"song_name": "Started From the Bottom",      "artist": "Drake",                  "album": "Nothing Was the Same",           "spotify_id": "4y7GNVnl0DSCG1EZrRCqJA", "popularity": 80, "genre": "hip-hop"},
        {"song_name": "God's Plan",                   "artist": "Drake",                  "album": "Scorpion",                       "spotify_id": "6DCZcSspjsKoFjzjrWoCdn", "popularity": 86, "genre": "hip-hop"},
        {"song_name": "Jumpman",                      "artist": "Drake & Future",         "album": "What a Time to Be Alive",        "spotify_id": "4kTSBCrMGQCAMhCXvpBBGI", "popularity": 79, "genre": "hip-hop"},
        {"song_name": "Hall of Fame",                 "artist": "The Script ft. will.i.am","album": "No Sound Without Silence",      "spotify_id": "6Vf3oXtb5MrN3Gb7p4fkxF", "popularity": 78, "genre": "pop-rock"},
        {"song_name": "Champion",                     "artist": "Kanye West ft. Santogold","album": "Graduation",                    "spotify_id": "1gfYFJGlk5xn7rTLGSMJBM", "popularity": 73, "genre": "hip-hop"},
        {"song_name": "Roar",                         "artist": "Katy Perry",             "album": "Prism",                          "spotify_id": "6DAYV98PFBkeaIEHr9yFKM", "popularity": 82, "genre": "pop"},
        {"song_name": "Firework",                     "artist": "Katy Perry",             "album": "Teenage Dream",                  "spotify_id": "57bgtoPSgt236HzfBOd8kj", "popularity": 81, "genre": "pop"},
        {"song_name": "Fight Song",                   "artist": "Rachel Platten",         "album": "Wildfire",                       "spotify_id": "05fG473iIaoy2BqF8ltUWu", "popularity": 79, "genre": "pop"},
        {"song_name": "Brave",                        "artist": "Sara Bareilles",         "album": "The Blessed Unrest",             "spotify_id": "4WwbWZ3XHFQLC1mFMzq8Kc", "popularity": 77, "genre": "pop"},
        {"song_name": "Rise Up",                      "artist": "Andra Day",              "album": "Cheers to the Fall",             "spotify_id": "2bIyLFHhiGNhXHqiQVPPxJ", "popularity": 78, "genre": "soul"},
        {"song_name": "This Is Me",                   "artist": "Keala Settle",           "album": "The Greatest Showman OST",       "spotify_id": "6PQ88X9TkUIAUIZJHW2upE", "popularity": 76, "genre": "pop"},
        {"song_name": "Unstoppable",                  "artist": "Sia",                    "album": "This Is Acting",                 "spotify_id": "6oHLbWKpGpEO2ikHcLYCdm", "popularity": 80, "genre": "pop"},
        {"song_name": "Run the World (Girls)",        "artist": "Beyoncé",                "album": "4",                              "spotify_id": "3QGsuHI8jO1Rx4JWLUh9jd", "popularity": 76, "genre": "pop"},
        {"song_name": "Power",                        "artist": "Kanye West",             "album": "My Beautiful Dark Twisted Fantasy","spotify_id": "2gZUPNdnz5Y45eiGxpHGSc", "popularity": 79, "genre": "hip-hop"},
        {"song_name": "Work Hard, Play Hard",         "artist": "Wiz Khalifa",            "album": "O.N.I.F.C.",                     "spotify_id": "7k5SUibfIZXtFBRbP3L7jz", "popularity": 73, "genre": "hip-hop"},
        {"song_name": "Can't Hold Us",                "artist": "Macklemore & Ryan Lewis", "album": "The Heist",                     "spotify_id": "4AcZFqroqYHqnr9gMBhGbP", "popularity": 78, "genre": "hip-hop"},
        {"song_name": "Thrift Shop",                  "artist": "Macklemore & Ryan Lewis", "album": "The Heist",                     "spotify_id": "0BEb0dNVGr9OQ4KYh3B5aH", "popularity": 77, "genre": "hip-hop"},
        {"song_name": "Stronger",                     "artist": "Kanye West",             "album": "Graduation",                     "spotify_id": "0gplL1WMoJ6iYaPgMCL0gX", "popularity": 82, "genre": "hip-hop"},
        {"song_name": "Welcome to the Jungle",        "artist": "Guns N' Roses",          "album": "Appetite for Destruction",       "spotify_id": "1T3KJleJFd6xFDFtUOFI5k", "popularity": 81, "genre": "hard-rock"},
        {"song_name": "We Will Rock You",             "artist": "Queen",                  "album": "News of the World",              "spotify_id": "54flyrjcdnQdco7300avMo", "popularity": 82, "genre": "rock"},
        {"song_name": "We Are the Champions",         "artist": "Queen",                  "album": "News of the World",              "spotify_id": "7f0vVL3xi4i78Rv5Ptn2s1", "popularity": 82, "genre": "rock"},
        {"song_name": "Harder Better Faster",         "artist": "Daft Punk",              "album": "Discovery",                      "spotify_id": "4ntOCKZGMAnAFkQdJpGQk2", "popularity": 79, "genre": "electronic"},
        {"song_name": "Run Boy Run",                  "artist": "Woodkid",                "album": "The Golden Age",                 "spotify_id": "3ZYpRiYuoHBkdP7bDKw1Xn", "popularity": 71, "genre": "indie-pop"},
        {"song_name": "Glory",                        "artist": "Common ft. John Legend", "album": "Selma OST",                      "spotify_id": "1ooV8BIiIqHaFbRm5OxLRq", "popularity": 71, "genre": "hip-hop"},
        {"song_name": "Ain't No Mountain High Enough","artist": "Marvin Gaye & Tammi Terrell","album": "United",                    "spotify_id": "7tqhbajSILNvGSqJOWgMBB", "popularity": 75, "genre": "soul"},
        {"song_name": "Gonna Fly Now (Theme from Rocky)","artist": "Bill Conti",         "album": "Rocky OST",                      "spotify_id": "4FnIBH71Bk9p5R5bHhwfQo", "popularity": 68, "genre": "soundtrack"},
        {"song_name": "Radioactive",                  "artist": "Imagine Dragons",        "album": "Night Visions",                  "spotify_id": "69yfbpvmkIaB10msnKT9UP", "popularity": 84, "genre": "alternative"},
        {"song_name": "Thunder",                      "artist": "Imagine Dragons",        "album": "Evolve",                         "spotify_id": "1zB4vmk8tFRmM9UULNzbLB", "popularity": 81, "genre": "alternative"},
        {"song_name": "Believer",                     "artist": "Imagine Dragons",        "album": "Evolve",                         "spotify_id": "0pqnGHJpmpxLKifKRmU6WP", "popularity": 83, "genre": "alternative"},
        {"song_name": "Run to the Hills",             "artist": "Iron Maiden",            "album": "The Number of the Beast",        "spotify_id": "5SuOikwiRyPMVoIQDJUgSV", "popularity": 66, "genre": "metal"},
        {"song_name": "The Final Countdown",          "artist": "Europe",                 "album": "The Final Countdown",            "spotify_id": "4Ejv3kHm8XtTmXaVFbgHNx", "popularity": 74, "genre": "rock"},
        {"song_name": "Back in Black",                "artist": "AC/DC",                  "album": "Back in Black",                  "spotify_id": "08mG3Y1vljYA6bvDt4Wqkj", "popularity": 80, "genre": "rock"},
        {"song_name": "Thunderstruck",                "artist": "AC/DC",                  "album": "The Razors Edge",                "spotify_id": "57bgtoPSgt236HzfBOd8kj", "popularity": 81, "genre": "rock"},
    ],

    # ══════════════════════════════════════════════════════════════
    #  PARTY  — EDM, dance, hip-hop bangers, club classics
    # ══════════════════════════════════════════════════════════════
    "party": [
        {"song_name": "Levels",                       "artist": "Avicii",                 "album": "Levels",                         "spotify_id": "0WqIKmW4BTrj3eJFmnCKMv", "popularity": 80, "genre": "edm"},
        {"song_name": "Wake Me Up",                   "artist": "Avicii",                 "album": "True",                           "spotify_id": "0nJW01T7XtvILxQgC5J7Wh", "popularity": 82, "genre": "edm"},
        {"song_name": "Titanium",                     "artist": "David Guetta ft. Sia",   "album": "Nothing but the Beat",           "spotify_id": "0FDzzruyVECATHd3yZqZ5L", "popularity": 81, "genre": "edm"},
        {"song_name": "Animals",                      "artist": "Martin Garrix",          "album": "Animals",                        "spotify_id": "1tcggBbZSPCIRxv7HkKONW", "popularity": 78, "genre": "edm"},
        {"song_name": "Faded",                        "artist": "Alan Walker",            "album": "Different World",                "spotify_id": "7BKLCZ1jbUBVqRi2FVlTVw", "popularity": 82, "genre": "edm"},
        {"song_name": "Lean On",                      "artist": "Major Lazer & MØ",       "album": "Peace Is the Mission",           "spotify_id": "7hR22TOX3RorxJPcsz5Wbo", "popularity": 83, "genre": "dancehall"},
        {"song_name": "Cheap Thrills",                "artist": "Sia",                    "album": "This Is Acting",                 "spotify_id": "4fLZJr5S8Rl47pOqRIBVMJ", "popularity": 82, "genre": "pop"},
        {"song_name": "In My Feelings",               "artist": "Drake",                  "album": "Scorpion",                       "spotify_id": "7lENXHnFECGEZUCMiRhBcF", "popularity": 83, "genre": "hip-hop"},
        {"song_name": "One Dance",                    "artist": "Drake",                  "album": "Views",                          "spotify_id": "1W8TbFzNS15VwsempfY12H", "popularity": 84, "genre": "dancehall"},
        {"song_name": "Work",                         "artist": "Rihanna",                "album": "Anti",                           "spotify_id": "5GorFiMnXDp0rUfBSJIgqw", "popularity": 81, "genre": "dancehall"},
        {"song_name": "Sorry",                        "artist": "Justin Bieber",          "album": "Purpose",                        "spotify_id": "69bp2EbF7Q2rqc5N3ylezZ", "popularity": 84, "genre": "pop"},
        {"song_name": "What Do You Mean?",            "artist": "Justin Bieber",          "album": "Purpose",                        "spotify_id": "7lEKnLhFUHMU6qRIfNRqhR", "popularity": 82, "genre": "pop"},
        {"song_name": "Night Changes",                "artist": "One Direction",          "album": "FOUR",                           "spotify_id": "6PCUP3dWmTjcTtXY02oFdT", "popularity": 81, "genre": "pop"},
        {"song_name": "Shake It Off",                 "artist": "Taylor Swift",           "album": "1989",                           "spotify_id": "0cqRj7pUJDkTCEsJkx8snD", "popularity": 88, "genre": "pop"},
        {"song_name": "Telephone",                    "artist": "Lady Gaga ft. Beyoncé",  "album": "The Fame Monster",               "spotify_id": "4HFanHrH4ZfVt5yiYwsnKz", "popularity": 79, "genre": "pop"},
        {"song_name": "Just Dance",                   "artist": "Lady Gaga",              "album": "The Fame",                       "spotify_id": "4XCBWOj3t8K6d6nFDQCEFT", "popularity": 78, "genre": "pop"},
        {"song_name": "Poker Face",                   "artist": "Lady Gaga",              "album": "The Fame",                       "spotify_id": "0TKjFMkqlXEEzAlkDPTcgE", "popularity": 81, "genre": "pop"},
        {"song_name": "Mirrors",                      "artist": "Justin Timberlake",      "album": "The 20/20 Experience",           "spotify_id": "2A9ZguqIs2QpVe4RGYXY1R", "popularity": 78, "genre": "pop"},
        {"song_name": "SexyBack",                     "artist": "Justin Timberlake",      "album": "FutureSex/LoveSounds",           "spotify_id": "2pPa4MJj3X7HlEaADOhSot", "popularity": 79, "genre": "pop"},
        {"song_name": "Lose Control",                 "artist": "Missy Elliott",          "album": "The Cookbook",                   "spotify_id": "5VGnCkLeHFHJQkaeQiMQVd", "popularity": 72, "genre": "hip-hop"},
        {"song_name": "Get Low",                      "artist": "Lil Jon & Ying Yang Twins","album": "Kings of Crunk",               "spotify_id": "2ZTQzCQhVi8wME3SEFdYJ6", "popularity": 72, "genre": "hip-hop"},
        {"song_name": "Yeah!",                        "artist": "Usher ft. Lil Jon & Ludacris","album": "Confessions",              "spotify_id": "0p7r6GHVgMJKixXCi1KGOB", "popularity": 78, "genre": "r-n-b"},
        {"song_name": "DJ Got Us Fallin' in Love",    "artist": "Usher ft. Pitbull",      "album": "Raymond v Raymond",              "spotify_id": "6FxEJiVjnoGKMXZKnOEqNV", "popularity": 74, "genre": "r-n-b"},
        {"song_name": "Live Your Life",               "artist": "T.I. ft. Rihanna",       "album": "Paper Trail",                    "spotify_id": "2Xb3wGOdHFECKxknxpZo1T", "popularity": 76, "genre": "hip-hop"},
        {"song_name": "Timber",                       "artist": "Pitbull ft. Kesha",      "album": "Globalization",                  "spotify_id": "3FUSUqKIRCo5XAcqYFGLO2", "popularity": 77, "genre": "pop"},
        {"song_name": "Feel This Moment",             "artist": "Pitbull ft. Christina Aguilera","album": "Global Warming",         "spotify_id": "2J3pOxkOTNDkHJhxuqrCjT", "popularity": 73, "genre": "pop"},
        {"song_name": "Boom",                         "artist": "Tiësto & Sevenn",        "album": "Boom",                           "spotify_id": "4c7E1UrjqPqJjJGi2EvBVi", "popularity": 71, "genre": "edm"},
        {"song_name": "Summer",                       "artist": "Calvin Harris",          "album": "Motion",                         "spotify_id": "7gkxDO36j1HzaQ7bCLbYMG", "popularity": 81, "genre": "edm"},
        {"song_name": "Feel So Close",                "artist": "Calvin Harris",          "album": "18 Months",                      "spotify_id": "0cmQiPMu5JiETGpqTFpyAe", "popularity": 77, "genre": "edm"},
        {"song_name": "Thinking About You",           "artist": "Calvin Harris",          "album": "18 Months",                      "spotify_id": "3YokX6Vh1djxCnkqKIj5G0", "popularity": 74, "genre": "edm"},
        {"song_name": "This Is What You Came For",    "artist": "Calvin Harris ft. Rihanna","album": "This Is What You Came For",   "spotify_id": "4Nm5HO3V8hTCeJAfZAUvnC", "popularity": 81, "genre": "edm"},
        {"song_name": "Lean On (Major Lazer)",        "artist": "Major Lazer",            "album": "Peace Is the Mission",           "spotify_id": "6PCUP3dWmTjcTtXY02oFdT", "popularity": 80, "genre": "edm"},
        {"song_name": "Lean On Me",                   "artist": "Bill Withers",           "album": "Still Bill",                     "spotify_id": "3lPr8ghNDBLc2uZovNyLs9", "popularity": 78, "genre": "soul"},
        {"song_name": "Party Rock Anthem",            "artist": "LMFAO ft. Lauren Bennett","album": "Sorry for Party Rocking",      "spotify_id": "6JuJfV9OlSdMlW08HJhTZH", "popularity": 76, "genre": "edm"},
        {"song_name": "Moves Like Jagger",            "artist": "Maroon 5 ft. Christina Aguilera","album": "Hands All Over",       "spotify_id": "6K1Y9UNJ9vLaJ7fcDhiQCp", "popularity": 79, "genre": "pop"},
        {"song_name": "Mr. Saxobeat",                 "artist": "Alexandra Stan",         "album": "Saxobeats",                      "spotify_id": "3qJPRjqCMxkxW3Qf5mGfU7", "popularity": 68, "genre": "pop"},
        {"song_name": "Turn Me On",                   "artist": "David Guetta ft. Nicki Minaj","album": "Nothing but the Beat",     "spotify_id": "1yIkJbk4MFWi0g1LVfBYTH", "popularity": 74, "genre": "edm"},
        {"song_name": "Born This Way",                "artist": "Lady Gaga",              "album": "Born This Way",                  "spotify_id": "6JvT19rJp9mI2JMbOo8yFb", "popularity": 79, "genre": "pop"},
        {"song_name": "Applause",                     "artist": "Lady Gaga",              "album": "ARTPOP",                         "spotify_id": "6x3iVq2MijBnpNv5aBCsqA", "popularity": 76, "genre": "pop"},
        {"song_name": "Rain on Me",                   "artist": "Lady Gaga & Ariana Grande","album": "Chromatica",                  "spotify_id": "0TFbbEGMHPVnPJlvRlVvpE", "popularity": 80, "genre": "pop"},
    ],

    # ══════════════════════════════════════════════════════════════
    #  STUDY  — lo-fi, classical, instrumental, ambient focus
    # ══════════════════════════════════════════════════════════════
    "study": [
        {"song_name": "Clair de Lune",                "artist": "Claude Debussy",         "album": "Suite bergamasque",              "spotify_id": "4Tr4HkA7PwTv1Gp1jCtRxR", "popularity": 74, "genre": "classical"},
        {"song_name": "Moonlight Sonata",             "artist": "Ludwig van Beethoven",   "album": "Piano Sonatas",                  "spotify_id": "3skn2lauGk7Dx6bVIt5DVj", "popularity": 70, "genre": "classical"},
        {"song_name": "Gymnopédie No. 1",             "artist": "Erik Satie",             "album": "Gymnopédies",                    "spotify_id": "5NGtFXVpXSvwunEIGeviY3", "popularity": 72, "genre": "classical"},
        {"song_name": "River Flows in You",           "artist": "Yiruma",                 "album": "First Love",                     "spotify_id": "4Ac1pZhLpOb5RvSA4YBkFx", "popularity": 74, "genre": "classical"},
        {"song_name": "Experience",                   "artist": "Ludovico Einaudi",       "album": "In a Time Lapse",                "spotify_id": "1BncfTJAWtL8MUBK3NCJDO", "popularity": 73, "genre": "classical"},
        {"song_name": "Nuvole Bianche",               "artist": "Ludovico Einaudi",       "album": "Una Mattina",                    "spotify_id": "1tpXaFOLiVEQD0IhcRkdUV", "popularity": 72, "genre": "classical"},
        {"song_name": "Divenire",                     "artist": "Ludovico Einaudi",       "album": "Divenire",                       "spotify_id": "05glPbZE7kB1oKIwt5QMQK", "popularity": 69, "genre": "classical"},
        {"song_name": "Comptine d'un autre été",      "artist": "Yann Tiersen",           "album": "Amélie OST",                     "spotify_id": "2ZPzKMM1bqbcVRJl9m3zFI", "popularity": 73, "genre": "classical"},
        {"song_name": "Canon in D",                   "artist": "Johann Pachelbel",       "album": "Canon in D",                     "spotify_id": "4MRr0i0yAMQUVJAtcEMuMY", "popularity": 68, "genre": "classical"},
        {"song_name": "Four Seasons - Spring",        "artist": "Antonio Vivaldi",        "album": "The Four Seasons",               "spotify_id": "6f6rR7rMm38NqOF7P0KkGW", "popularity": 67, "genre": "classical"},
        {"song_name": "Weightless",                   "artist": "Marconi Union",          "album": "Weightless",                     "spotify_id": "6qqNVTkY8uBg9cP3Jd7DAH", "popularity": 65, "genre": "ambient"},
        {"song_name": "An Ending (Ascent)",           "artist": "Brian Eno",              "album": "Apollo: Atmospheres and Soundtracks","spotify_id": "5q0TkmCpEuEzHSHVqlhm1K", "popularity": 60, "genre": "ambient"},
        {"song_name": "Music for Airports",           "artist": "Brian Eno",              "album": "Ambient 1: Music for Airports",  "spotify_id": "0m5t4BNeepEL9G6RcE6coa", "popularity": 59, "genre": "ambient"},
        {"song_name": "First Breath After Coma",      "artist": "Explosions in the Sky",  "album": "The Earth Is Not a Cold Dead Place","spotify_id": "0GTz1R2fFbQKaaSZt2GFEG", "popularity": 64, "genre": "post-rock"},
        {"song_name": "Your Hand in Mine",            "artist": "Explosions in the Sky",  "album": "The Earth Is Not a Cold Dead Place","spotify_id": "1rCvMXbLOsFjSfBQ8GBCeR", "popularity": 65, "genre": "post-rock"},
        {"song_name": "Glósóli",                      "artist": "Sigur Rós",              "album": "Takk...",                        "spotify_id": "1Z5UpNdSTz3DGM7rKOVSuA", "popularity": 65, "genre": "post-rock"},
        {"song_name": "Ára bátur",                    "artist": "Sigur Rós",              "album": "Með suð í eyrum við spilum endalaust","spotify_id": "3t7jJFGU0CJ7bNwrHXjK3L", "popularity": 62, "genre": "post-rock"},
        {"song_name": "Study Lofi - Beats to Relax", "artist": "Lo-Fi Boy",              "album": "Lofi Hip Hop Music",             "spotify_id": "5F5qBZq0MIjn5LQAqX3hUE", "popularity": 63, "genre": "lo-fi"},
        {"song_name": "coffee",                       "artist": "beabadoobee",            "album": "Loveworm",                       "spotify_id": "7E5BFMjUo5a3AzQb0aJ4G0", "popularity": 76, "genre": "indie"},
        {"song_name": "Retrograde",                   "artist": "James Blake",            "album": "Overgrown",                      "spotify_id": "2dgOxkZkExHTj7lBbkGSKA", "popularity": 72, "genre": "electronic"},
        {"song_name": "Holocene",                     "artist": "Bon Iver",               "album": "Bon Iver, Bon Iver",             "spotify_id": "7sOR7gk6XKnHopCAUSFVBo", "popularity": 74, "genre": "indie-folk"},
        {"song_name": "Stairway to Heaven (Acoustic)","artist": "Led Zeppelin",          "album": "Led Zeppelin IV",                "spotify_id": "5CQ30WqJwcep0pYcV4AMNc", "popularity": 78, "genre": "rock"},
        {"song_name": "Only Time",                    "artist": "Enya",                   "album": "A Day Without Rain",             "spotify_id": "4IFbsWRTzz3cVbr73kXcOH", "popularity": 72, "genre": "new-age"},
        {"song_name": "Orinoco Flow",                 "artist": "Enya",                   "album": "Watermark",                      "spotify_id": "4jfzBQ0TkM2jSUhS6OGriX", "popularity": 71, "genre": "new-age"},
        {"song_name": "Porcelain",                    "artist": "Moby",                   "album": "Play",                           "spotify_id": "4ZSZWyDFHXJGBSBWqAKIJU", "popularity": 67, "genre": "electronic"},
        {"song_name": "God Moving Over the Face of the Waters","artist": "Moby",         "album": "Everything Is Wrong",            "spotify_id": "4hRWuVCh7Cl6CxKh2zMwk4", "popularity": 64, "genre": "electronic"},
        {"song_name": "Carbon Based Lifeforms",       "artist": "Carbon Based Lifeforms", "album": "World of Sleepers",              "spotify_id": "3VBfQ8gBuSGSUBB0u2XnuH", "popularity": 58, "genre": "ambient"},
        {"song_name": "Uyama Hiroto - Feather",       "artist": "Uyama Hiroto",           "album": "A Son of the Sun",               "spotify_id": "5IFxNhECjMxXpkX7pBxJkv", "popularity": 60, "genre": "lo-fi"},
        {"song_name": "La Valse d'Amélie",            "artist": "Yann Tiersen",           "album": "Amélie OST",                     "spotify_id": "4JdTKy9tX0ZSCbHH8ILwfd", "popularity": 68, "genre": "classical"},
        {"song_name": "The Departure",                "artist": "Ludovico Einaudi",       "album": "Taranta Project",                "spotify_id": "3VNbXDJcZvqPWkVvAvdEPN", "popularity": 65, "genre": "classical"},
        {"song_name": "Una Mattina",                  "artist": "Ludovico Einaudi",       "album": "Una Mattina",                    "spotify_id": "67MVGHfkzPDQIdL8b5gXOX", "popularity": 67, "genre": "classical"},
        {"song_name": "In the Bleak Midwinter",       "artist": "Loreena McKennitt",      "album": "To Drive the Cold Winter Away",  "spotify_id": "3OvBFjJKtHWVijG0m0dBVi", "popularity": 60, "genre": "folk"},
        {"song_name": "Sleep",                        "artist": "Max Richter",            "album": "Sleep",                          "spotify_id": "4VZ7jhV6MVtO3PrABhzLfP", "popularity": 64, "genre": "classical"},
        {"song_name": "November",                     "artist": "Max Richter",            "album": "The Blue Notebooks",             "spotify_id": "4a3MCnNF1JzR71KlJvH7OC", "popularity": 65, "genre": "classical"},
        {"song_name": "On the Nature of Daylight",    "artist": "Max Richter",            "album": "The Blue Notebooks",             "spotify_id": "6HAyMaH4pM1MKPNxBaqCJU", "popularity": 68, "genre": "classical"},
        {"song_name": "Metamorphosis Two",            "artist": "Philip Glass",           "album": "Metamorphosis",                  "spotify_id": "1YnopD3T4HiDyBQq2DKXEZ", "popularity": 63, "genre": "classical"},
        {"song_name": "Mad Rush",                     "artist": "Philip Glass",           "album": "Solo Piano",                     "spotify_id": "0K2qfBdQxwxX3TOUOa63mX", "popularity": 61, "genre": "classical"},
        {"song_name": "Aqueous Transmission",         "artist": "Incubus",                "album": "Morning View",                   "spotify_id": "0Ml7JqSi8rrOHHpg6JIJHK", "popularity": 68, "genre": "alternative"},
        {"song_name": "Atlas Hands",                  "artist": "Benjamin Francis Leftwich","album": "Last Smoke Before the Snowstorm","spotify_id": "5xjyqWHOiIBVHJNTJ9zHjJ", "popularity": 63, "genre": "indie-folk"},
        {"song_name": "Skinny Love",                  "artist": "Birdy",                  "album": "Birdy",                          "spotify_id": "1mea3bSkSGXuIRvnydlB5b", "popularity": 71, "genre": "indie-pop"},
    ],
}


def get_songs_for_mood(mood: str) -> list:
    """Return the full curated song list for a given mood."""
    return SONG_CATALOG.get(mood.lower(), [])


def get_all_songs() -> list:
    """Return every song across all moods as a flat list (with mood field added)."""
    all_songs = []
    for mood, songs in SONG_CATALOG.items():
        for song in songs:
            all_songs.append({**song, "mood": mood})
    return all_songs


def get_catalog_stats() -> dict:
    """Return per-mood and total song counts."""
    stats = {mood: len(songs) for mood, songs in SONG_CATALOG.items()}
    stats["total"] = sum(stats.values())
    return stats
